version: "2.1"

services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - web 

  web:
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate && 
                      gunicorn -c gunicorn.py evolutio.wsgi"
    volumes:
      - ./evolutio:/code
    expose:
      - 8001
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aploschadny





