# Generated by Django 3.2.7 on 2022-07-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryproduct',
            name='delivery_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_delivery_product', to='test_api.delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryproduct',
            name='product_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_delivery_product', to='test_api.product'),
        ),
    ]
